---
apiVersion: core.gardener.cloud/v1
kind: ControllerDeployment
metadata:
  name: extension-shoot-pack
helm:
  ociRepository:
    ref: registry.local.gardener.cloud:5001/helm-charts/gardener-extension-shoot-pack:v0.1.0-dev
  values: {}
