//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	config "github.com/gardener/gardener-extension-shoot-pack/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*PackConfig)(nil), (*config.PackConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackConfig_To_config_PackConfig(a.(*PackConfig), b.(*config.PackConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.PackConfig)(nil), (*PackConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_PackConfig_To_v1alpha1_PackConfig(a.(*config.PackConfig), b.(*PackConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackConfigSpec)(nil), (*config.PackConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackConfigSpec_To_config_PackConfigSpec(a.(*PackConfigSpec), b.(*config.PackConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.PackConfigSpec)(nil), (*PackConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_PackConfigSpec_To_v1alpha1_PackConfigSpec(a.(*config.PackConfigSpec), b.(*PackConfigSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_PackConfig_To_config_PackConfig(in *PackConfig, out *config.PackConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_PackConfigSpec_To_config_PackConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PackConfig_To_config_PackConfig is an autogenerated conversion function.
func Convert_v1alpha1_PackConfig_To_config_PackConfig(in *PackConfig, out *config.PackConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackConfig_To_config_PackConfig(in, out, s)
}

func autoConvert_config_PackConfig_To_v1alpha1_PackConfig(in *config.PackConfig, out *PackConfig, s conversion.Scope) error {
	if err := Convert_config_PackConfigSpec_To_v1alpha1_PackConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_PackConfig_To_v1alpha1_PackConfig is an autogenerated conversion function.
func Convert_config_PackConfig_To_v1alpha1_PackConfig(in *config.PackConfig, out *PackConfig, s conversion.Scope) error {
	return autoConvert_config_PackConfig_To_v1alpha1_PackConfig(in, out, s)
}

func autoConvert_v1alpha1_PackConfigSpec_To_config_PackConfigSpec(in *PackConfigSpec, out *config.PackConfigSpec, s conversion.Scope) error {
	out.Foo = in.Foo
	return nil
}

// Convert_v1alpha1_PackConfigSpec_To_config_PackConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_PackConfigSpec_To_config_PackConfigSpec(in *PackConfigSpec, out *config.PackConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackConfigSpec_To_config_PackConfigSpec(in, out, s)
}

func autoConvert_config_PackConfigSpec_To_v1alpha1_PackConfigSpec(in *config.PackConfigSpec, out *PackConfigSpec, s conversion.Scope) error {
	out.Foo = in.Foo
	return nil
}

// Convert_config_PackConfigSpec_To_v1alpha1_PackConfigSpec is an autogenerated conversion function.
func Convert_config_PackConfigSpec_To_v1alpha1_PackConfigSpec(in *config.PackConfigSpec, out *PackConfigSpec, s conversion.Scope) error {
	return autoConvert_config_PackConfigSpec_To_v1alpha1_PackConfigSpec(in, out, s)
}
