apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: extension-shoot-pack
spec:
  deployment:
    extension:
      helm:
        ociRepository:
          ref: registry.local.gardener.cloud:5001/helm-charts/gardener-extension-shoot-pack:v0.1.0-dev
  resources:
    - kind: Extension
      type: shoot-pack
