//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackConfig) DeepCopyInto(out *PackConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackConfig.
func (in *PackConfig) DeepCopy() *PackConfig {
	if in == nil {
		return nil
	}
	out := new(PackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PackConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackConfigSpec) DeepCopyInto(out *PackConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackConfigSpec.
func (in *PackConfigSpec) DeepCopy() *PackConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PackConfigSpec)
	in.DeepCopyInto(out)
	return out
}
