apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-controller-manager-config
  namespace: kube-system
  labels:
    helm.sh/chart: cloudnative-pg-0.27.1
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/instance: extension
    app.kubernetes.io/version: "1.28.1"
    app.kubernetes.io/managed-by: Helm
data:
  {}
