apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: extension-shoot-pack
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  resources:
    - kind: Extension
      type: shoot-pack
      workerlessSupported: true
      clusterCompatibility:
        - shoot
      lifecycle:
        reconcile: BeforeKubeAPIServer
        delete: AfterKubeAPIServer
        migrate: AfterKubeAPIServer
