{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.extension.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.extension.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.extension.metrics.enable_scraping }}
    - port: {{ .Values.extension.metrics.bind_address | trimPrefix ":" }}
      targetPort: {{ .Values.extension.metrics.bind_address | trimPrefix ":" }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Values.extension.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end}}
